[manager]
show_hidden = true

[preview]
wrap = "yes"
image_delay = 0

[opener]
open = [
    { run = 'xdg-open "$@"', orphan = true, desc = "Open" },
]
images_preview = [
    { run = 'feh -Fq --start-at "$@" --on-last-slide hold .', desc = "Preview" },
]
pinta = [
    { run = 'pinta "$@"', desc = "Edit with Pinta" },
]

[open]
prepend_rules = [
    { mime = "image/*", use = [ "images_preview", "pinta" ] },
]
